# -*- coding: utf-8 -*-
"""ObjectClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Mw-iwk0lyR4xY3hyaBsjJuf0cpaJEKzI
"""

import tensorflow as tf
import numpy as np
from tensorflow import keras
import matplotlib.pyplot as plt
from keras import layers

tf.config.experimental.list_physical_devices()

(X_train,y_train),(X_test,y_test)=tf.keras.datasets.cifar10.load_data()

def sample(index):
    plt.figure(figsize=(10,1))
    plt.imshow(X_train[index])

labels=['airoplane','automobiles','bird','cat','deer','dog','frog','horse','ship','truck']

X_train=X_train.astype('float64')/255.0
X_test=X_test.astype('float64')/255.0

y_train_Categorical=keras.utils.to_categorical(
    y_train, num_classes=10,dtype='float32'
)
y_train_Categorical

y_test_Categorical=keras.utils.to_categorical(
    y_test, num_classes=10,dtype='float32'
)
y_test_Categorical

model=keras.Sequential(
[
    keras.layers.Flatten(input_shape=(32,32,3)),
    layers.Dense(3000,activation='relu'),
    layers.Dense(1000,activation='relu'),
    layers.Dense(10),
])

model.compile(
    loss=keras.losses.CategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=['accuracy'],
)

model.fit(X_train,y_train_Categorical,epochs=10,verbose=2)

model.evaluate(X_test,y_test_Categorical,epochs=10,verbose=2)